## License 

Copyright 2020 Patrick Hall (jphall@gwu.edu)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

**DISCLAIMER:** This notebook is not legal compliance advice.

***

# Attacking a Constrained Machine Learning Model

#### Global hyperpameters

In [1]:
SEED = 12345 # global random seed for better reproducibility

#### Python imports and inits

In [2]:
from rmltk import debug, evaluate, model # simple module for evaluating, debugging, and training models

# h2o Python API with specific classes
import h2o                                        
from h2o.estimators.gbm import H2OGradientBoostingEstimator # for GBM

import numpy as np   # array, vector, matrix calculations
import pandas as pd  # DataFrame handling

import matplotlib.pyplot as plt # general plotting
pd.options.display.max_columns = 999 # enable display of all columns in notebook

# display plots in-notebook
%matplotlib inline   

h2o.init(max_mem_size='2G')      # start h2o
h2o.remove_all()                 # remove any existing data structures from h2o memory

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "1.8.0_252"; OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09); OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
  Starting server from /home/patrickh/Workspace/GWU_rml/env_rml/lib/python3.6/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpwbigsuw9
  JVM stdout: /tmp/tmpwbigsuw9/h2o_patrickh_started_from_python.out
  JVM stderr: /tmp/tmpwbigsuw9/h2o_patrickh_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is too old (9 months and 10 days)! Please download and install the latest version from http://h2o.ai/download/

--------------------------  ---------------------------------------------------
H2O cluster uptime:         00 secs
H2O cluster timezone:       America/New_York
H2O data parsing timezone:  UTC
H2O cluster version:        3.26.0.3
H2O cluster version age:    9 months and 10 days !!!
H2O cluster name:           H2O_from_python_patrickh_8fev5r
H2O cluster total nodes:    1
H2O cluster free memory:    1.879 Gb
H2O cluster total cores:    24
H2O cluster allowed cores:  24
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.6.9 final
--------------------------  ---------------------------------------------------

## 1. Download, Explore, and Prepare UCI Credit Card Default Data

UCI credit card default data: https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

The UCI credit card default data contains demographic and payment information about credit card customers in Taiwan in the year 2005. The data set contains 23 input variables: 

* **`LIMIT_BAL`**: Amount of given credit (NT dollar)
* **`SEX`**: 1 = male; 2 = female
* **`EDUCATION`**: 1 = graduate school; 2 = university; 3 = high school; 4 = others 
* **`MARRIAGE`**: 1 = married; 2 = single; 3 = others
* **`AGE`**: Age in years 
* **`PAY_0`, `PAY_2` - `PAY_6`**: History of past payment; `PAY_0` = the repayment status in September, 2005; `PAY_2` = the repayment status in August, 2005; ...; `PAY_6` = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; ...; 8 = payment delay for eight months; 9 = payment delay for nine months and above. 
* **`BILL_AMT1` - `BILL_AMT6`**: Amount of bill statement (NT dollar). `BILL_AMNT1` = amount of bill statement in September, 2005; `BILL_AMT2` = amount of bill statement in August, 2005; ...; `BILL_AMT6` = amount of bill statement in April, 2005. 
* **`PAY_AMT1` - `PAY_AMT6`**: Amount of previous payment (NT dollar). `PAY_AMT1` = amount paid in September, 2005; `PAY_AMT2` = amount paid in August, 2005; ...; `PAY_AMT6` = amount paid in April, 2005. 

Demographic variables will not be used as model inputs as is common in credit scoring models. However, demographic variables will be used after model training to test for disparate impact.

#### Import data and clean

In [3]:
# import XLS file
path = 'default_of_credit_card_clients.xls'
data = pd.read_excel(path,
                     skiprows=1)

# remove spaces from target column name 
data = data.rename(columns={'default payment next month': 'DEFAULT_NEXT_MONTH'})

#### Assign modeling roles

In [4]:
# assign target and inputs for GBM
y_name = 'DEFAULT_NEXT_MONTH'
x_names = [name for name in data.columns if name not in [y_name, 'ID', 'AGE', 'EDUCATION', 'MARRIAGE', 'SEX']]
print('y =', y_name)
print('X =', x_names)

y = DEFAULT_NEXT_MONTH
X = ['LIMIT_BAL', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

#### Helper function for recoding values in the UCI credict card default data
This simple function maps longer, more understandable character string values from the UCI credit card default data dictionary to the original integer values of the input variables found in the dataset.

In [5]:
def recode_cc_data(frame):
    
    """ Recodes numeric categorical variables into categorical character variables
    with more transparent values. 
    
    Args:
        frame: Pandas DataFrame version of UCI credit card default data.
        
    Returns: 
        H2OFrame with recoded values.
        
    """
    
    # define recoded values
    sex_dict = {1:'male', 2:'female'}
    education_dict = {0:'other', 1:'graduate school', 2:'university', 3:'high school', 
                      4:'other', 5:'other', 6:'other'}
    marriage_dict = {0:'other', 1:'married', 2:'single', 3:'divorced'}
    
    # recode values using apply() and lambda function
    frame['SEX'] = frame['SEX'].apply(lambda i: sex_dict[i])
    frame['EDUCATION'] = frame['EDUCATION'].apply(lambda i: education_dict[i])    
    frame['MARRIAGE'] = frame['MARRIAGE'].apply(lambda i: marriage_dict[i])           
                
    return h2o.H2OFrame(frame)

data = recode_cc_data(data)

Parse progress: |█████████████████████████████████████████████████████████| 100%

#### Split data into training and validation partitions
Fairness metrics will be calculated for the validation data to give a better idea of how explanations will look on future unseen data.

In [6]:
# split into training and validation
train, valid = data.split_frame([0.7], seed=12345)

# summarize split
print('Train data rows = %d, columns = %d' % (train.shape[0], train.shape[1]))
print('Validation data rows = %d, columns = %d' % (valid.shape[0], valid.shape[1]))

Train data rows = 21060, columns = 25
Validation data rows = 8940, columns = 25

## 2. Load Pre-trained Monotonic GBM
Load the model known as `mgbm5` from the first lecture.

In [7]:
# load saved best model from lecture 1 
best_mgbm = h2o.load_model('best_mgbm')

# display model details
best_mgbm

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  best_mgbm


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,46.0,46.0,6939.0,3.0,3.0,3.0,5.0,8.0,7.369565

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.13637719864300343
RMSE: 0.3692928358945018
LogLoss: 0.4351274080189972
Mean Per-Class Error: 0.2913939696264273
AUC: 0.7716491282246187
pr_auc: 0.5471826859054356
Gini: 0.5432982564492375

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.21968260039166268:

                0       1   Error               Rate
0      0  13482.0  2814.0  0.1727   (2814.0/16296.0)
1      1   1907.0  2743.0  0.4101    (1907.0/4650.0)
2  Total  15389.0  5557.0  0.2254   (4721.0/20946.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                        metric  threshold     value    idx
0                       max f1   0.219683  0.537474  248.0
1                       max f2   0.127859  0.630227  329.0
2                 max f0point5   0.446699  0.583033  147.0
3                 max accuracy   0.446699  0.821493  147.0
4                max precision   0.950247  1.000000    0.0
5                   max recall   0.050609  1.000000  395.0
6              max specificity   0.950247  1.000000    0.0
7             max absolute_mcc   0.325159  0.413494  194.0
8   max min_per_class_accuracy   0.177542  0.698495  281.0
9  max mean_per_class_accuracy   0.219683  0.708606  248.0

Gains/Lift Table: Avg response rate: 22.20 %, avg score: 22.00 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010074,0.813927,3.607883,3.607883,0.800948,0.843446,0.800948,0.843446,0.036344,0.036344,260.788259,260.788259
1,,2,0.020338,0.795575,3.519808,3.563432,0.781395,0.805153,0.791080,0.824119,0.036129,0.072473,251.980795,256.343177
2,,3,0.030316,0.763679,3.405328,3.511394,0.755981,0.783970,0.779528,0.810905,0.033978,0.106452,240.532798,251.139446
3,,4,0.040008,0.715138,3.261891,3.450954,0.724138,0.739815,0.766110,0.793684,0.031613,0.138065,226.189099,245.095388
4,,5,0.050081,0.664416,3.116869,3.383755,0.691943,0.686695,0.751192,0.772164,0.031398,0.169462,211.686898,238.375473
5,,6,0.100019,0.543384,2.859463,3.121984,0.634799,0.601794,0.693079,0.687101,0.142796,0.312258,185.946339,212.198445
6,,7,0.150005,0.366237,2.224293,2.822849,0.493792,0.446951,0.626671,0.607076,0.111183,0.423441,122.429306,182.284922
7,,8,0.205672,0.292765,1.595510,2.490659,0.354202,0.312777,0.552925,0.527422,0.088817,0.512258,59.551043,149.065864
8,,9,0.301251,0.196648,1.174504,2.073077,0.260739,0.234499,0.460222,0.434485,0.112258,0.624516,17.450421,107.307684
9,,10,0.400029,0.173817,0.864327,1.774604,0.191880,0.184844,0.393961,0.372842,0.085376,0.709892,-13.567284,77.460410
10,,11,0.500286,0.151431,0.701418,1.559537,0.155714,0.161335,0.346216,0.330455,0.070323,0.780215,-29.858249,55.953665
11,,12,0.600306,0.131214,0.619237,1.402870,0.137470,0.140709,0.311436,0.298841,0.061935,0.842151,-38.076342,40.286982
12,,13,0.700659,0.114794,0.559314,1.282050,0.124167,0.122817,0.284614,0.273630,0.056129,0.898280,-44.068568,28.204987
13,,14,0.800821,0.102226,0.369293,1.167887,0.081983,0.108062,0.259270,0.252921,0.036989,0.935269,-63.070697,16.788724
14,,15,0.904564,0.091861,0.402152,1.080066,0.089277,0.097524,0.239774,0.235099,0.041720,0.976989,-59.784808,8.006633
15,,16,1.000000,0.034810,0.241112,1.000000,0.053527,0.076989,0.221999,0.220010,0.023011,1.000000,-75.888783,0.000000

ModelMetricsBinomial: gbm
** Reported on validation data. **

MSE: 0.13326994104124376
RMSE: 0.3650615578792757
LogLoss: 0.4278285715046422
Mean Per-Class Error: 0.2856607030196092
AUC: 0.7776380047998697
pr_auc: 0.5486322626112021
Gini: 0.5552760095997393

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.27397344199105433:

               0       1   Error              Rate
0      0  6093.0   975.0  0.1379    (975.0/7068.0)
1      1   863.0  1123.0  0.4345    (863.0/1986.0)
2  Total  6956.0  2098.0   0.203   (1838.0/9054.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                        metric  threshold     value    idx
0                       max f1   0.273973  0.549951  217.0
1                       max f2   0.147835  0.634488  307.0
2                 max f0point5   0.436620  0.590736  153.0
3                 max accuracy   0.456963  0.825271  147.0
4                max precision   0.947069  1.000000    0.0
5                   max recall   0.045106  1.000000  397.0
6              max specificity   0.947069  1.000000    0.0
7             max absolute_mcc   0.347246  0.429999  184.0
8   max min_per_class_accuracy   0.181585  0.709970  275.0
9  max mean_per_class_accuracy   0.230518  0.714339  240.0

Gains/Lift Table: Avg response rate: 21.94 %, avg score: 22.52 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.011155,0.815010,3.295055,3.295055,0.722772,0.839858,0.722772,0.839858,0.036757,0.036757,229.505549,229.505549
1,,2,0.020543,0.795575,3.700764,3.480460,0.811765,0.805631,0.763441,0.824217,0.034743,0.071501,270.076417,248.045999
2,,3,0.030042,0.783550,3.604721,3.519749,0.790698,0.792441,0.772059,0.814170,0.034240,0.105740,260.472142,251.974853
3,,4,0.040093,0.743192,3.005876,3.390927,0.659341,0.761335,0.743802,0.800925,0.030211,0.135952,200.587630,239.092657
4,,5,0.050033,0.697702,3.444512,3.401573,0.755556,0.723091,0.746137,0.785461,0.034240,0.170191,244.451158,240.157260
5,,6,0.101281,0.553193,3.104777,3.251394,0.681034,0.614736,0.713195,0.699075,0.159114,0.329305,210.477654,225.139444
6,,7,0.150320,0.383564,2.187046,2.904171,0.479730,0.466067,0.637032,0.623061,0.107251,0.436556,118.704581,190.417123
7,,8,0.200022,0.296915,1.580423,2.575244,0.346667,0.327817,0.564881,0.549698,0.078550,0.515106,58.042296,157.524427
8,,9,0.301303,0.203539,1.133514,2.090616,0.248637,0.250648,0.458578,0.449174,0.114804,0.629909,13.351366,109.061561
9,,10,0.403468,0.176970,0.961068,1.804595,0.210811,0.187190,0.395839,0.382836,0.098187,0.728097,-3.893198,80.459549
10,,11,0.500221,0.152028,0.655734,1.582382,0.143836,0.163566,0.347096,0.340424,0.063444,0.791541,-34.426603,58.238248
11,,12,0.599956,0.133009,0.555349,1.411651,0.121816,0.141651,0.309647,0.307381,0.055388,0.846928,-44.465076,41.165144
12,,13,0.702231,0.115062,0.492323,1.277757,0.107991,0.123549,0.280277,0.280607,0.050352,0.897281,-50.767685,27.775745
13,,14,0.801966,0.102380,0.353404,1.162802,0.077519,0.107834,0.255061,0.259121,0.035247,0.932528,-64.659594,16.280206
14,,15,0.905346,0.091861,0.379909,1.073405,0.083333,0.097585,0.235452,0.240675,0.039275,0.971803,-62.009063,7.340501
15,,16,1.000000,0.034810,0.297899,1.000000,0.065344,0.076884,0.219351,0.225172,0.028197,1.000000,-70.210141,0.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error,validation_rmse,validation_logloss,validation_auc,validation_pr_auc,validation_lift,validation_classification_error
0,,2020-05-28 14:33:23,43.415 sec,0.0,0.415591,0.529427,0.500000,0.000000,1.000000,0.778001,0.413815,0.526105,0.500000,0.000000,1.000000,0.780649
1,,2020-05-28 14:33:23,43.443 sec,1.0,0.407822,0.511864,0.716131,0.534717,3.474912,0.236370,0.405538,0.507496,0.726731,0.537125,3.444264,0.187652
2,,2020-05-28 14:33:23,43.467 sec,2.0,0.401483,0.498746,0.744646,0.532172,3.529706,0.228731,0.398808,0.493698,0.752909,0.534588,3.422307,0.232825
3,,2020-05-28 14:33:23,43.489 sec,3.0,0.396471,0.489013,0.748189,0.535621,3.529706,0.228636,0.393394,0.483273,0.756448,0.535692,3.422307,0.214491
4,,2020-05-28 14:33:23,43.515 sec,4.0,0.392442,0.481430,0.750121,0.535358,3.529706,0.210780,0.389030,0.475135,0.758511,0.536095,3.422307,0.217915
5,,2020-05-28 14:33:23,43.535 sec,5.0,0.389141,0.475375,0.750058,0.535198,3.529706,0.245059,0.385453,0.468630,0.758505,0.535659,3.422307,0.214270
6,,2020-05-28 14:33:23,43.570 sec,6.0,0.386399,0.470332,0.756986,0.535024,3.529706,0.243961,0.382447,0.463157,0.764722,0.536039,3.422307,0.229843
7,,2020-05-28 14:33:23,43.592 sec,7.0,0.384191,0.466316,0.757005,0.535418,3.529706,0.243961,0.380045,0.458834,0.764634,0.536411,3.422307,0.220013
8,,2020-05-28 14:33:23,43.614 sec,8.0,0.382341,0.462760,0.761106,0.540176,3.514359,0.247446,0.378063,0.455049,0.770340,0.542043,3.457524,0.204330
9,,2020-05-28 14:33:23,43.639 sec,9.0,0.380701,0.459589,0.762515,0.540880,3.518279,0.235654,0.376184,0.451464,0.772358,0.543522,3.457524,0.223548
10,,2020-05-28 14:33:23,43.668 sec,10.0,0.379202,0.456705,0.762522,0.541424,3.518279,0.235606,0.374583,0.448380,0.772982,0.543893,3.457524,0.226309
11,,2020-05-28 14:33:23,43.697 sec,11.0,0.378052,0.454467,0.761648,0.541505,3.521332,0.231023,0.373354,0.445973,0.772925,0.544553,3.460882,0.228960
12,,2020-05-28 14:33:23,43.729 sec,12.0,0.377043,0.452420,0.762767,0.541658,3.521332,0.229972,0.372199,0.443670,0.773412,0.543195,3.460882,0.224542
13,,2020-05-28 14:33:23,43.762 sec,13.0,0.376137,0.450517,0.764795,0.543264,3.525899,0.234317,0.371369,0.441932,0.774161,0.543632,3.448038,0.227413
14,,2020-05-28 14:33:23,43.796 sec,14.0,0.375357,0.448963,0.765145,0.543113,3.525899,0.235654,0.370549,0.440335,0.774176,0.543202,3.448038,0.228076
15,,2020-05-28 14:33:23,43.848 sec,15.0,0.374699,0.447543,0.766118,0.544037,3.528417,0.233219,0.369999,0.439161,0.774592,0.543709,3.448038,0.228297
16,,2020-05-28 14:33:23,43.903 sec,16.0,0.374098,0.446341,0.766529,0.543896,3.560713,0.229161,0.369390,0.437926,0.775021,0.544851,3.424855,0.226751
17,,2020-05-28 14:33:23,43.949 sec,17.0,0.373534,0.445115,0.766312,0.544208,3.568370,0.231452,0.368810,0.436669,0.774927,0.545957,3.442929,0.225425
18,,2020-05-28 14:33:23,44.004 sec,18.0,0.373121,0.444171,0.766785,0.544720,3.568370,0.229352,0.368496,0.435909,0.775256,0.545586,3.442929,0.226530
19,,2020-05-28 14:33:23,44.054 sec,19.0,0.372722,0.443360,0.767145,0.545059,3.568370,0.226439,0.368047,0.435006,0.775474,0.545922,3.442929,0.224652

See the whole table with table.as_data_frame()

Variable Importances:

    variable  relative_importance  scaled_importance  percentage
0      PAY_0          2794.444824           1.000000    0.693347
1      PAY_2           307.237366           0.109946    0.076231
2      PAY_3           215.152893           0.076993    0.053383
3      PAY_4           155.434448           0.055623    0.038566
4   PAY_AMT1           127.986313           0.045800    0.031755
5      PAY_5           127.538628           0.045640    0.031644
6      PAY_6           102.351601           0.036627    0.025395
7  LIMIT_BAL            82.432350           0.029499    0.020453
8   PAY_AMT2            58.934135           0.021090    0.014623
9   PAY_AMT4            58.858047           0.021063    0.014604

#### Shutdown H2O

In [28]:
# be careful, this can erase your work!
h2o.cluster().shutdown(prompt=True)

Are you sure you want to shutdown the H2O instance running at http://127.0.0.1:54321 (Y/N)? n